#!/usr/bin/env python3
"""Generate port/gen/AssetData.pas embedding every game asset as Pascal
const byte arrays, for the single-exe build (socher_single.lpr).

Bundled: socher1/*.scr, *.win, *.sgn, *.lin and FONTHE8.COM.
Deliberately NOT bundled: winners.win and port.cfg - those are the player's
persistent data, created next to the extracted assets at runtime.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC_DIR = os.path.join(ROOT, "socher1")
OUT_PATH = os.path.join(ROOT, "port", "gen", "AssetData.pas")

EXTENSIONS = {".scr", ".win", ".sgn", ".lin"}
EXTRA_FILES = {"fonthe8.com"}
EXCLUDE = {"winners.win"}


def wanted(name: str) -> bool:
    lower = name.lower()
    if lower in EXCLUDE:
        return False
    return os.path.splitext(lower)[1] in EXTENSIONS or lower in EXTRA_FILES


FACTORY_WINNERS = os.path.join(ROOT, "port", "data", "winners-factory.win")


def main() -> None:
    files = sorted(f for f in os.listdir(SRC_DIR) if wanted(f))
    if not files:
        sys.exit("no assets found in " + SRC_DIR)

    parts = []
    parts.append("unit AssetData;\n")
    parts.append("{ GENERATED by port/tools/embed_assets.py - do not edit. }\n")
    parts.append("{$mode objfpc}\n")
    parts.append("interface\n\n")
    parts.append("const\n")
    parts.append(f"  AssetCount = {len(files)};\n\n")
    parts.append("function AssetName(Index: Integer): string;\n")
    parts.append("function AssetPtr(Index: Integer): Pointer;\n")
    parts.append("function AssetSize(Index: Integer): LongInt;\n\n")

    winners = open(FACTORY_WINNERS, "rb").read()
    parts.append("const\n")
    parts.append("  { The pristine high-score file shipped with the original game;\n")
    parts.append("    extracted only when the player has no winners.win yet }\n")
    parts.append(f"  FactoryWinners: array[0..{len(winners) - 1}] of byte = (\n")
    parts.append("    " + ",".join(str(b) for b in winners) + "\n  );\n\n")

    parts.append("implementation\n\n")

    for i, name in enumerate(files):
        data = open(os.path.join(SRC_DIR, name), "rb").read()
        parts.append(f"const\n  Asset{i}: array[0..{len(data) - 1}] of byte = (\n")
        line = []
        for j, b in enumerate(data):
            line.append(str(b))
            if len(line) == 24:
                sep = "," if j + 1 < len(data) else ""
                parts.append("    " + ",".join(line) + sep + "\n")
                line = []
        if line:
            parts.append("    " + ",".join(line) + "\n")
        parts.append("  );\n\n")

    parts.append("function AssetName(Index: Integer): string;\n")
    parts.append("begin\n  case Index of\n")
    for i, name in enumerate(files):
        parts.append(f"    {i}: AssetName := '{name.lower()}';\n")
    parts.append("  else\n    AssetName := '';\n  end;\nend;\n\n")

    parts.append("function AssetPtr(Index: Integer): Pointer;\n")
    parts.append("begin\n  case Index of\n")
    for i in range(len(files)):
        parts.append(f"    {i}: AssetPtr := @Asset{i}[0];\n")
    parts.append("  else\n    AssetPtr := nil;\n  end;\nend;\n\n")

    parts.append("function AssetSize(Index: Integer): LongInt;\n")
    parts.append("begin\n  case Index of\n")
    for i, name in enumerate(files):
        size = os.path.getsize(os.path.join(SRC_DIR, name))
        parts.append(f"    {i}: AssetSize := {size};\n")
    parts.append("  else\n    AssetSize := 0;\n  end;\nend;\n\n")
    parts.append("end.\n")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", newline="\n") as out:
        out.write("".join(parts))
    total = sum(os.path.getsize(os.path.join(SRC_DIR, f)) for f in files)
    print(f"wrote {OUT_PATH}: {len(files)} assets, {total} bytes embedded")


if __name__ == "__main__":
    main()
